### ISSUE TITLE
Error: Type '"Maybe"' does not satisfy the constraint 'never'

### ISSUE THREAD

**Issue by xiaoxiangmoe** [joshburgess/tagged-ts#2] opened 2020-06-10 03:57 UTC
```ts

type Nothing = { readonly tag: 'Nothing' };
type Just<A> = {
  readonly tag: 'Just';
  readonly value: A;
};
type Maybe<A> = Just<A> | Nothing;

interface MaybeSpec<A> {
  readonly type: Maybe<A>;
  readonly data: {
    readonly Just: Just<A>;
    readonly Nothing: Nothing;
  };
}

declare module 'tagged-ts/lib/Registry' {
  interface TypeConstructorRegistry1<A> {
    readonly Maybe: MaybeSpec<A>;
  }
}
import { __, mkTaggedUnion } from 'tagged-ts';

// `__` is used as a general purpose placeholder for when keys are needed at
// run-time, but values are not
export const Maybe = mkTaggedUnion<'Maybe'>()({ // Type '"Maybe"' does not satisfy the constraint 'never'.ts(2344)
  Just: { tag: __, value: __ },
  Nothing: { tag: __ },
});
```

```json
{
  "dependencies": {
    "tagged-ts": "^0.1.6",
    "typescript": "^3.9.5"
  }
}
```

```json
{
  "compilerOptions": {
    "strict": true
  }
}
```

**Comment by joshburgess** [comment] 2020-06-13 23:14
@xiaoxiangmoe Okay, I have now fixed the problem. Due to the library being previously broken because of this issue, I unpublished all old versions and have reset the library to version 0.2.0. The build will work as intended now.

While investigating the problem, I tried what I described above (adding examples to each of the type constructor registries), but this didn't solve the problem. Instead of `TypeURI extends never`, I was getting `TypeURI extends _`, where `_` was a union of the keys of the examples I added to each registry.

So, this was essentially still the same problem. The way the type aliases collapse down when building the .d.ts files for the build makes these constraints incompatible with using module augmentation to add new specs to the type constructor registries. So, I went back to empty registries, and, to get around the problem, I am just hand editing these constraints in the built .d.ts files & docs to change the constraints back to `TypeURI extends KeyOfTypeConstructorRegistry`, like it is in the library's source code.

This isn't ideal from a maintenance/build perspective, but it works. To ensure that I don't accidentally publish bad builds, I added some extra steps to the build/publish process (using `prepublishOnly`) to generate some files that use the code from the built `lib` and `es6` files and run `tsc` on them to make sure things type-check correctly. If they don't type-check, `prepublishOnly` will fail, returning an error code that escapes out of the publish process.

This will work for now. In the future, I'd like to make things a little more automated. I'd like to try to replace the `TypeURI extends never` in the built TS definition files and generated docs with `TypeURI extends KeyOfTypeConstructorRegistry` automatically so that I don't have to edit them by hand each time I create a new release, but this would be a nice-to-have, and what I'm doing right now solves the problem.

I am going to close this issue now. Thanks for bringing this to my attention.

**Closed by joshburgess** 2020-06-13 23:14 UTC
